// High-reliability In-Memory Store Fallback for V-TACS

export const mockStore = {
  hospitals: [
    {
      id: 1,
      name: "Sassoon General Hospital (Apex Trauma)",
      latitude: 18.5262,
      longitude: 73.8738,
      current_asv_vials: 85,
      ventilator_available: 1,
      is_open: 1,
      accepting_patients: 1,
      is_24_7: 1,
      opening_time: "00:00",
      closing_time: "23:59",
      facility_category: "TERTIARY_APEX",
      phone: "+91-20-26128000",
      address: "Near Pune Railway Station, Sassoon Road, Pune"
    },
    {
      id: 2,
      name: "YCM Hospital (Yashwantrao Chavan Memorial)",
      latitude: 18.6279,
      longitude: 73.8188,
      current_asv_vials: 42,
      ventilator_available: 1,
      is_open: 1,
      accepting_patients: 1,
      is_24_7: 1,
      opening_time: "00:00",
      closing_time: "23:59",
      facility_category: "TERTIARY_APEX",
      phone: "+91-20-27422500",
      address: "Pimpri Colony, Pimpri-Chinchwad, Pune"
    },
    {
      id: 3,
      name: "District Hospital Aundh",
      latitude: 18.5602,
      longitude: 73.8122,
      current_asv_vials: 28,
      ventilator_available: 1,
      is_open: 1,
      accepting_patients: 1,
      is_24_7: 1,
      opening_time: "00:00",
      closing_time: "23:59",
      facility_category: "TERTIARY_APEX",
      phone: "+91-20-27290111",
      address: "Aundh Camp, Medipoint Hospital Road, Pune"
    },
    {
      id: 4,
      name: "Chakan Unregistered Rural PHC",
      latitude: 18.7617,
      longitude: 73.8587,
      current_asv_vials: 0,
      ventilator_available: 0,
      is_open: 1,
      accepting_patients: 1,
      is_24_7: 0,
      opening_time: "08:00",
      closing_time: "20:00",
      facility_category: "UNREGISTERED_PHC",
      phone: "+91-2135-222300",
      address: "Shikrapur Road, Chakan, Maharashtra"
    },
    {
      id: 5,
      name: "Shirur Rural Government Hospital",
      latitude: 18.8278,
      longitude: 74.3789,
      current_asv_vials: 4,
      ventilator_available: 0,
      is_open: 1,
      accepting_patients: 1,
      is_24_7: 0,
      opening_time: "08:00",
      closing_time: "20:00",
      facility_category: "GENERAL_SECONDARY",
      phone: "+91-2138-222150",
      address: "Pune-Nagar Highway, Shirur, Maharashtra"
    },
    {
      id: 6,
      name: "Hadapsar Emergency Trauma & Venom Care",
      latitude: 18.5089,
      longitude: 73.9260,
      current_asv_vials: 30,
      ventilator_available: 1,
      is_open: 1,
      accepting_patients: 1,
      is_24_7: 1,
      opening_time: "00:00",
      closing_time: "23:59",
      facility_category: "TERTIARY_APEX",
      phone: "+91-20-26871234",
      address: "Solapur Road, Hadapsar, Pune"
    },
    {
      id: 7,
      name: "Talegaon General Hospital & ICU",
      latitude: 18.7300,
      longitude: 73.6800,
      current_asv_vials: 15,
      ventilator_available: 1,
      is_open: 1,
      accepting_patients: 1,
      is_24_7: 1,
      opening_time: "00:00",
      closing_time: "23:59",
      facility_category: "GENERAL_SECONDARY",
      phone: "+91-2114-223400",
      address: "Station Road, Talegaon Dabhade, Maharashtra"
    },
    {
      id: 8,
      name: "Pune Eye & Laser Specialty Clinic (EXCLUDED)",
      latitude: 18.5200,
      longitude: 73.8500,
      current_asv_vials: 0,
      ventilator_available: 0,
      is_open: 1,
      accepting_patients: 1,
      is_24_7: 0,
      opening_time: "09:00",
      closing_time: "18:00",
      facility_category: "SPECIALTY_EXCLUDED",
      phone: "+91-20-25500000",
      address: "JM Road, Shivajinagar, Pune"
    }
  ],
  ambulances: [
    {
      id: 1,
      vehicle_number: "MH-12-EM-1081",
      current_lat: 18.5314,
      current_lon: 73.8446,
      status: "available",
      driver_name: "Suresh Shinde",
      driver_phone: "+91-9822011111",
      last_ping_time: new Date().toISOString()
    },
    {
      id: 2,
      vehicle_number: "MH-12-EM-1082",
      current_lat: 18.7550,
      current_lon: 73.8500,
      status: "available",
      driver_name: "Ramesh Pawar",
      driver_phone: "+91-9822022222",
      last_ping_time: new Date().toISOString()
    },
    {
      id: 3,
      vehicle_number: "MH-12-EM-1083",
      current_lat: 18.5020,
      current_lon: 73.9300,
      status: "available",
      driver_name: "Mahesh Jadhav",
      driver_phone: "+91-9822033333",
      last_ping_time: new Date().toISOString()
    },
    {
      id: 4,
      vehicle_number: "MH-12-EM-1084",
      current_lat: 18.6250,
      current_lon: 73.8100,
      status: "dispatched",
      driver_name: "Aniket Kulkarni",
      driver_phone: "+91-9822044444",
      last_ping_time: new Date().toISOString()
    }
  ],
  active_cases: [
    {
      id: 101,
      victim_lat: 18.7500,
      victim_lon: 73.8600,
      location_description: "Near Chakan Market Yard",
      symptoms: "Bitten on ankle 40 min ago. Severe local swelling, ptosis, slurred speech.",
      victim_blood_group: "O+ Positive",
      victim_medical_history: "Hypertension",
      victim_emergency_contact: "+91-9876543210",
      bite_time: new Date(Date.now() - 40 * 60000).toISOString(),
      assigned_hospital_id: 1,
      assigned_hospital_name: "Sassoon General Hospital (Apex Trauma)",
      assigned_ambulance_id: 4,
      assigned_ambulance_number: "MH-12-EM-1084",
      estimated_eta: 22,
      asv_vials_reserved: 10,
      status: "dispatched",
      created_at: new Date(Date.now() - 40 * 60000).toISOString()
    }
  ]
};
